type SeedItem = {
  name: string
  price: number
}

export type SeedSale = {
  seller_id: string
  title: string
  city: string
  state: string
  address: string
  lat: number
  lng: number
  starts_at: string
  ends_at: string
  categories: string[]
  cover_image_url: string | null
  items: SeedItem[]
}

const SELLER = 'b2750036-4a71-404a-9020-1734b5b888b1'

// Helper to make local ISO strings (no timezone suffix) like 2025-10-04T08:00:00
function localISO(date: string, time: string): string {
  return `${date}T${time}:00`
}

export const SEED_DATA: SeedSale[] = [
  {
    seller_id: SELLER,
    title: 'Highlands Community Yard Sale — Louisville, KY',
    city: 'Louisville',
    state: 'KY',
    address: 'Bardstown Rd & Eastern Pkwy',
    lat: 38.2350,
    lng: -85.7080,
    starts_at: localISO('2025-10-04', '08:00'),
    ends_at: localISO('2025-10-04', '12:00'),
    categories: ['furniture','kids','decor'],
    cover_image_url: null,
    items: [
      { name: 'Wood Dining Table', price: 80.00 },
      { name: 'Kids’ Bike 20in', price: 45.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Crescent Hill Multi-Family — Louisville, KY',
    city: 'Louisville',
    state: 'KY',
    address: 'Frankfort Ave',
    lat: 38.2640,
    lng: -85.6990,
    starts_at: localISO('2025-10-05', '09:00'),
    ends_at: localISO('2025-10-05', '13:00'),
    categories: ['tools','electronics'],
    cover_image_url: null,
    items: [
      { name: 'Cordless Drill', price: 35.00 },
      { name: 'Bluetooth Speaker', price: 25.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Downtown Lexington Garage Sale — Lexington, KY',
    city: 'Lexington',
    state: 'KY',
    address: 'Short St & N Limestone',
    lat: 38.0406,
    lng: -84.5037,
    starts_at: localISO('2025-10-04', '08:00'),
    ends_at: localISO('2025-10-04', '12:00'),
    categories: ['books','sports','kitchen','home'],
    cover_image_url: null,
    items: [
      { name: 'Golf Clubs (mixed)', price: 60.00 },
      { name: 'Cookware Set', price: 40.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'East Nashville Porch Sale — Nashville, TN',
    city: 'Nashville',
    state: 'TN',
    address: 'Eastland Ave',
    lat: 36.1800,
    lng: -86.7400,
    starts_at: localISO('2025-10-05', '09:00'),
    ends_at: localISO('2025-10-05', '13:00'),
    categories: ['vintage','music','clothing'],
    cover_image_url: null,
    items: [
      { name: 'Vintage Record Player', price: 70.00 },
      { name: 'Band Tees (bundle)', price: 25.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Over-the-Rhine Alley Sale — Cincinnati, OH',
    city: 'Cincinnati',
    state: 'OH',
    address: 'Vine St',
    lat: 39.1100,
    lng: -84.5150,
    starts_at: localISO('2025-10-04', '08:00'),
    ends_at: localISO('2025-10-04', '12:00'),
    categories: ['art','kitchen','plants','decor'],
    cover_image_url: null,
    items: [
      { name: 'Potted Succulents (3)', price: 15.00 },
      { name: 'Cast Iron Skillet', price: 20.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Broad Ripple Neighborhood Sale — Indianapolis, IN',
    city: 'Indianapolis',
    state: 'IN',
    address: 'College Ave',
    lat: 39.8700,
    lng: -86.1450,
    starts_at: localISO('2025-10-05', '09:00'),
    ends_at: localISO('2025-10-05', '13:00'),
    categories: ['kids','games','tools'],
    cover_image_url: null,
    items: [
      { name: 'Board Games (lot)', price: 18.00 },
      { name: 'Socket Set', price: 22.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Tower Grove Park Community — St. Louis, MO',
    city: 'St. Louis',
    state: 'MO',
    address: 'Arsenal St',
    lat: 38.6070,
    lng: -90.2540,
    starts_at: localISO('2025-10-04', '08:00'),
    ends_at: localISO('2025-10-04', '12:00'),
    categories: ['furniture','garden'],
    cover_image_url: null,
    items: [
      { name: 'Patio Chairs (pair)', price: 35.00 },
      { name: 'Hand Tiller', price: 12.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Evanston Block Sale — Evanston, IL',
    city: 'Evanston',
    state: 'IL',
    address: 'Main St',
    lat: 42.0451,
    lng: -87.6877,
    starts_at: localISO('2025-10-05', '09:00'),
    ends_at: localISO('2025-10-05', '13:00'),
    categories: ['books','clothing','small-appliances'],
    cover_image_url: null,
    items: [
      { name: 'Toaster Oven', price: 15.00 },
      { name: 'Hardcover Novels (5)', price: 20.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Inman Park Yard Sale — Atlanta, GA',
    city: 'Atlanta',
    state: 'GA',
    address: 'Edgewood Ave',
    lat: 33.7610,
    lng: -84.3520,
    starts_at: localISO('2025-10-04', '08:00'),
    ends_at: localISO('2025-10-04', '12:00'),
    categories: ['decor','electronics','toys'],
    cover_image_url: null,
    items: [
      { name: 'Smart Lamp', price: 25.00 },
      { name: 'LEGO Bundle', price: 30.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Short North Sidewalk Sale — Columbus, OH',
    city: 'Columbus',
    state: 'OH',
    address: 'High St',
    lat: 39.9790,
    lng: -83.0030,
    starts_at: localISO('2025-10-05', '09:00'),
    ends_at: localISO('2025-10-05', '13:00'),
    categories: ['art','fashion','home'],
    cover_image_url: null,
    items: [
      { name: 'Framed Print', price: 20.00 },
      { name: 'Throw Pillows (2)', price: 12.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Squirrel Hill Porch Hop — Pittsburgh, PA',
    city: 'Pittsburgh',
    state: 'PA',
    address: 'Murray Ave',
    lat: 40.4387,
    lng: -79.9230,
    starts_at: localISO('2025-10-02', '17:00'),
    ends_at: localISO('2025-10-02', '19:00'),
    categories: ['books','collectibles','vintage'],
    cover_image_url: null,
    items: [
      { name: 'Baseball Cards (binder)', price: 50.00 },
      { name: 'First Edition Novel', price: 35.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Plaza District Sale — Kansas City, MO',
    city: 'Kansas City',
    state: 'MO',
    address: 'Ward Pkwy',
    lat: 39.0400,
    lng: -94.5880,
    starts_at: localISO('2025-10-11', '08:00'),
    ends_at: localISO('2025-10-11', '12:00'),
    categories: ['fashion','art','decor'],
    cover_image_url: null,
    items: [
      { name: 'Designer Scarf', price: 28.00 },
      { name: 'Wall Mirror', price: 30.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Five Points Community — Raleigh, NC',
    city: 'Raleigh',
    state: 'NC',
    address: 'Glenwood Ave',
    lat: 35.8000,
    lng: -78.6370,
    starts_at: localISO('2025-10-12', '09:00'),
    ends_at: localISO('2025-10-12', '13:00'),
    categories: ['kids','toys','clothing'],
    cover_image_url: null,
    items: [
      { name: 'Toddler Toys (bin)', price: 15.00 },
      { name: 'Winter Coats (2)', price: 25.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Mueller Neighborhood Sale — Austin, TX',
    city: 'Austin',
    state: 'TX',
    address: 'Aldrich St',
    lat: 30.3030,
    lng: -97.7000,
    starts_at: localISO('2025-10-11', '08:00'),
    ends_at: localISO('2025-10-11', '12:00'),
    categories: ['electronics','appliances','office'],
    cover_image_url: null,
    items: [
      { name: '24" Monitor', price: 45.00 },
      { name: 'Coffee Maker', price: 20.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Arcadia Driveway Sale — Phoenix, AZ',
    city: 'Phoenix',
    state: 'AZ',
    address: 'Camelback Rd',
    lat: 33.4940,
    lng: -111.9860,
    starts_at: localISO('2025-10-12', '09:00'),
    ends_at: localISO('2025-10-12', '13:00'),
    categories: ['outdoor','tools','garden'],
    cover_image_url: null,
    items: [
      { name: 'Lawn Mower', price: 90.00 },
      { name: 'Pruning Shears', price: 12.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Wash Park Community — Denver, CO',
    city: 'Denver',
    state: 'CO',
    address: 'S Downing St',
    lat: 39.7000,
    lng: -104.9730,
    starts_at: localISO('2025-10-11', '08:00'),
    ends_at: localISO('2025-10-11', '12:00'),
    categories: ['sports','furniture'],
    cover_image_url: null,
    items: [
      { name: 'Ski Boots', price: 55.00 },
      { name: 'Side Table', price: 25.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Ballard Yard Sale — Seattle, WA',
    city: 'Seattle',
    state: 'WA',
    address: 'Market St',
    lat: 47.6680,
    lng: -122.3850,
    starts_at: localISO('2025-10-12', '09:00'),
    ends_at: localISO('2025-10-12', '13:00'),
    categories: ['vintage','collectibles','music'],
    cover_image_url: null,
    items: [
      { name: 'Vinyl Records (10)', price: 40.00 },
      { name: 'Vintage Camera', price: 60.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Alberta Arts Sale — Portland, OR',
    city: 'Portland',
    state: 'OR',
    address: 'NE Alberta St',
    lat: 45.5590,
    lng: -122.6430,
    starts_at: localISO('2025-10-11', '08:00'),
    ends_at: localISO('2025-10-11', '12:00'),
    categories: ['art','decor','fashion'],
    cover_image_url: null,
    items: [
      { name: 'Handmade Prints', price: 30.00 },
      { name: 'Lamp', price: 18.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'North Park Multi-Family — San Diego, CA',
    city: 'San Diego',
    state: 'CA',
    address: 'University Ave',
    lat: 32.7430,
    lng: -117.1290,
    starts_at: localISO('2025-10-05', '09:00'),
    ends_at: localISO('2025-10-05', '13:00'),
    categories: ['small-appliances','kitchen','games'],
    cover_image_url: null,
    items: [
      { name: 'Air Fryer', price: 35.00 },
      { name: 'Puzzle Bundle', price: 14.00 },
    ],
  },
  {
    seller_id: SELLER,
    title: 'Astoria Community Sale — Queens, NY',
    city: 'Queens',
    state: 'NY',
    address: '30th Ave',
    lat: 40.7640,
    lng: -73.9230,
    starts_at: localISO('2025-10-04', '08:00'),
    ends_at: localISO('2025-10-04', '12:00'),
    categories: ['fashion','appliances','electronics'],
    cover_image_url: null,
    items: [
      { name: 'Blender', price: 18.00 },
      { name: 'Headphones', price: 22.00 },
    ],
  },
]


